import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#111827',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#1f2937',
    padding: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  compactCard: {
    width: 112,
    backgroundColor: '#0f172a',
    borderRadius: 14,
    padding: 2,
    borderWidth: 1,
    borderColor: '#243244',
    overflow: 'hidden',
  },
  thumbWrap: {
    width: 96,
    height: 96,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#172033',
    position: 'relative',
  },
  compactThumbWrap: {
    height: 64,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#172033',
    marginBottom: 6,
    position: 'relative',
  },
  thumb: {
    width: '100%',
    height: '100%',
  },
  thumbFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  playBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(15,23,42,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  durationBadge: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    backgroundColor: 'rgba(2,6,23,0.78)',
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  durationText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  content: {
    flex: 1,
    gap: 2,
  },
  name: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
    marginBottom: 4,
  },
  meta: {
    color: '#cbd5e1',
    fontSize: 10,
    marginBottom: 2,
  },
  compactMeta: {
    color: '#cbd5e1',
    fontSize: 9,
    paddingLeft: 2,
  },
  path: {
    color: '#6b7280',
    fontSize: 11,
    marginTop: 8,
    lineHeight: 16,
  },
});
