import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cameraWrap: {flex: 1, backgroundColor: '#000'},
  topOverlay: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  badge: {
    backgroundColor: 'rgba(17,24,39,0.9)',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  badgeText: {color: '#dc2626', fontWeight: '700', fontSize: 12},
  recordingStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timerPill: {
    backgroundColor: 'rgba(17,24,39,0.9)',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  timerText: {
    color: '#f8fafc',
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  fpsText: {
    color: '#e5e7eb',
    backgroundColor: 'rgba(17,24,39,0.7)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    overflow: 'hidden',
    maxWidth: '66%',
  },
  audioStatusWrap: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 112,
    zIndex: 10,
  },
  audioStatusPill: {
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    gap: 2,
  },
  audioStatusPillSafe: {
    backgroundColor: 'rgba(5, 46, 22, 0.9)',
    borderColor: '#166534',
  },
  audioStatusPillWarning: {
    backgroundColor: 'rgba(120, 53, 15, 0.92)',
    borderColor: '#ea580c',
  },
  audioStatusPillTitle: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
  },
  audioStatusPillText: {
    color: '#e5e7eb',
    fontSize: 12,
    lineHeight: 17,
  },
  controls: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    gap: 12,
    alignItems: 'center',
    zIndex: 10,
  },
  controlsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    gap: 18,
  },
  controlsSideSlot: {
    width: 56,
    height: 56,
  },
  recordButton: {
    width: 60,
    height: 60,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ef4444',
    borderWidth: 5,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  recordButtonActive: {
    backgroundColor: '#dc2626',
  },
  recordButtonInner: {
    backgroundColor: '#fff',
    width: 30,
    height: 30,
  },
  cameraSwitchButton: {
    width: 40,
    height: 40,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(17, 24, 39, 0.1)',
    borderWidth: 1,
    borderColor: '#fff',
  },
  cameraSwitchButtonDisabled: {
    opacity: 0.45,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#0b1020',
  },
  title: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 21,
  },
});
