import {StyleSheet} from 'react-native';

import {cinematicTheme} from '../../theme/cinematicTheme';

const {colors, radii, typography} = cinematicTheme;

export const styles = StyleSheet.create({
  cameraWrap: {flex: 1, backgroundColor: colors.background},
  cameraVignetteTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  cameraVignetteBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 220,
    backgroundColor: 'rgba(0,0,0,0.26)',
  },
  recordingFrame: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    bottom: 10,
    borderRadius: 42,
    borderWidth: 1,
    borderColor: 'transparent',
    zIndex: 4,
  },
  topOverlay: {
    position: 'absolute',
    top: 10,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  badge: {
    backgroundColor: 'rgba(21, 16, 12, 0.9)',
    borderRadius: radii.pill,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeText: {
    color: colors.rec,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.8,
  },
  recordingStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timerPill: {
    backgroundColor: 'rgba(21, 16, 12, 0.9)',
    borderRadius: radii.pill,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  timerText: {
    color: colors.foreground,
    fontWeight: '700',
    fontFamily: typography.mono.fontFamily,
    fontVariant: ['tabular-nums'],
  },
  fpsText: {
    color: colors.foreground,
    backgroundColor: 'rgba(21, 16, 12, 0.72)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    maxWidth: '66%',
    fontFamily: typography.mono.fontFamily,
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'left',
  },
  audioStatusWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 122,
    zIndex: 10,
  },
  audioQuickMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 11,
  },
  audioStatusPill: {
    borderRadius: radii.lg,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    gap: 2,
    backgroundColor: colors.surface,
  },
  audioStatusPillSafe: {
    borderColor: 'rgba(53, 193, 119, 0.35)',
  },
  audioStatusPillWarning: {
    borderColor: 'rgba(247, 162, 36, 0.5)',
  },
  audioStatusPillTitle: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '800',
  },
  audioStatusPillText: {
    color: colors.mutedForeground,
    fontSize: 12,
    lineHeight: 17,
  },
  controls: {
    position: 'absolute',
    bottom: 22,
    left: 12,
    right: 12,
    gap: 12,
    alignItems: 'center',
    zIndex: 12,
  },
  controlsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    gap: 18,
  },
  controlsSideSlot: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  controlsSideSlotPlaceholder: {
    width: 56,
    height: 56,
  },
  audioProfileButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(21, 16, 12, 0.78)',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  audioProfileButtonLive: {
    backgroundColor: 'rgba(53, 193, 119, 0.16)',
    borderColor: 'rgba(53, 193, 119, 0.55)',
  },
  audioProfileButtonCustom: {
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
    borderColor: colors.accent,
  },
  audioQuickMenu: {
    position: 'absolute',
    bottom: 60,
    left: -4,
    width: 196,
    borderRadius: radii.lg,
    padding: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 8,
    shadowColor: '#020617',
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: {width: 0, height: 8},
    elevation: 12,
  },
  audioQuickMenuTitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  audioQuickMenuSubtitle: {
    color: colors.mutedForeground,
    fontSize: 12,
    marginTop: -2,
  },
  audioQuickOption: {
    borderRadius: radii.md,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: 'transparent',
    gap: 3,
  },
  audioQuickOptionSelectedStandard: {
    backgroundColor: 'rgba(247, 162, 36, 0.12)',
    borderColor: colors.accent,
  },
  audioQuickOptionSelectedLive: {
    backgroundColor: 'rgba(53, 193, 119, 0.16)',
    borderColor: colors.success,
  },
  audioQuickOptionSelectedCustom: {
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
    borderColor: colors.accent,
  },
  audioQuickOptionLabel: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '700',
  },
  audioQuickOptionLabelSelectedStandard: {
    color: colors.accent,
  },
  audioQuickOptionLabelSelectedLive: {
    color: colors.success,
  },
  audioQuickOptionLabelSelectedCustom: {
    color: colors.accent,
  },
  audioQuickOptionDescription: {
    color: colors.mutedForeground,
    fontSize: 11,
    lineHeight: 15,
  },
  recordButton: {
    width: 68,
    height: 68,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(250, 248, 245, 0.06)',
    borderWidth: 3,
    borderColor: 'rgba(250, 248, 245, 0.92)',
  },
  recordButtonActive: {
    backgroundColor: 'rgba(250, 248, 245, 0.06)',
  },
  recordButtonInner: {
    backgroundColor: colors.rec,
    width: 42,
    height: 42,
  },
  recordButtonInnerRecording: {
    width: 34,
    height: 34,
  },
  cameraSwitchButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(21, 16, 12, 0.78)',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  cameraSwitchButtonDisabled: {
    opacity: 0.45,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: colors.background,
  },
  title: {
    color: colors.foreground,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: typography.display.fontFamily,
  },
  subtitle: {
    color: colors.mutedForeground,
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 21,
    fontFamily: typography.body.fontFamily,
  },
});
