import {StyleSheet} from 'react-native';
import {cinematicTheme} from '../../theme/cinematicTheme';

const {colors, radii, typography} = cinematicTheme;

export const styles = StyleSheet.create({
  headerActions: {
    width: '100%',
    flexDirection: 'row',
    paddingHorizontal: 14,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  rightGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  headerIconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerIconButtonDisabled: {
    opacity: 0.35,
  },
  headerOptimizationButton: {
    marginRight: 4,
  },
  headerAmbientButton: {
    marginRight: 4,
  },
  optimizationMenuExpanded: {
    width: '100%',
    borderRadius: radii.lg,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: {width: 0, height: 10},
    elevation: 12,
  },
  optimizationMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optimizationMenuTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 2.2,
  },
  optimizationCloseButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optimizationMenuOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  optimizationOption: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  optimizationOptionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optimizationOptionIconWrapSelected: {
    borderColor: colors.accent,
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
  },
  optimizationOptionLabel: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 16,
  },
  optimizationOptionLabelSelected: {
    color: colors.accent,
  },
  recordingModeSection: {
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  recordingModeTitle: {
    color: colors.mutedForeground,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    fontFamily: typography.mono.fontFamily,
  },
  recordingModeOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  recordingModeOption: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.md,
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  recordingModeOptionSelected: {
    borderColor: colors.accent,
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
  },
  recordingModeOptionLabel: {
    color: colors.foreground,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
    fontFamily: typography.body.fontFamily,
  },
  recordingModeOptionLabelSelected: {
    color: colors.accent,
  },
  resolutionSection: {
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  resolutionTitle: {
    color: colors.mutedForeground,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    fontFamily: typography.mono.fontFamily,
  },
  resolutionOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  resolutionOption: {
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radii.md,
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resolutionOptionSelected: {
    borderColor: colors.accent,
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
  },
  resolutionOptionLabel: {
    color: colors.foreground,
    fontSize: 11,
    fontWeight: '800',
    fontFamily: typography.body.fontFamily,
  },
  resolutionOptionLabelSelected: {
    color: colors.accent,
  },
  ambientAnalysisOptionDescription: {
    color: colors.mutedForeground,
    fontSize: 11,
    lineHeight: 15,
    fontFamily: typography.body.fontFamily,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    textAlign: 'center',
  },
  optimizationButtonNone: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
  },
  optimizationButtonVideo: {
    borderWidth: 1,
    borderColor: colors.info,
    backgroundColor: 'rgba(59, 172, 218, 0.12)',
  },
  optimizationButtonAudio: {
    borderWidth: 1,
    borderColor: colors.success,
    backgroundColor: 'rgba(53, 193, 119, 0.12)',
  },
  optimizationButtonBoth: {
    borderWidth: 1,
    borderColor: colors.rec,
    backgroundColor: 'rgba(255, 47, 58, 0.12)',
  },
  ambientAnalysisButtonNone: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
  },
  ambientAnalysisButtonActive: {
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
  },
  ambientAnalysisButtonRunning: {
    borderWidth: 1,
    borderColor: colors.success,
    backgroundColor: 'rgba(53, 193, 119, 0.12)',
  },
});
