import {StyleSheet} from 'react-native';

import {cinematicTheme} from '../../theme/cinematicTheme';

const {colors, radii, typography} = cinematicTheme;

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  content: {paddingHorizontal: 16, paddingBottom: 22},
  header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerRightPlaceholder: {width: 34},
  headerEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 2.2,
    textTransform: 'uppercase',
    fontFamily: typography.mono.fontFamily,
  },
  title: {
    color: colors.foreground,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    fontFamily: typography.display.fontFamily,
  },
  subtitle: {
    color: colors.mutedForeground,
    marginTop: 8,
    marginBottom: 10,
    lineHeight: 20,
    fontFamily: typography.body.fontFamily,
  },
  label: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    fontFamily: typography.body.fontFamily,
  },
  helper: {
    color: colors.mutedForeground,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: typography.body.fontFamily,
  },
  sectionSpacer: {height: 14},
  bottomSpacer: {height: 24},
  audioStatusBox: {
    borderRadius: radii.lg,
    padding: 14,
    borderWidth: 1,
  },
  audioStatusBoxSafe: {
    backgroundColor: 'rgba(53, 193, 119, 0.08)',
    borderColor: 'rgba(53, 193, 119, 0.34)',
  },
  audioStatusBoxWarning: {
    backgroundColor: 'rgba(247, 162, 36, 0.08)',
    borderColor: 'rgba(247, 162, 36, 0.34)',
  },
  audioStatusTitle: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    fontFamily: typography.body.fontFamily,
  },
  audioStatusText: {
    color: colors.mutedForeground,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: typography.body.fontFamily,
  },
  resetButton: {
    marginTop: 14,
    alignSelf: 'flex-start',
    backgroundColor: colors.surface2,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  resetText: {color: colors.foreground, fontWeight: '700', fontFamily: typography.body.fontFamily},
  exportButton: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.accent,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
  },
  exportText: {
    color: colors.accentForeground,
    fontWeight: '800',
    fontFamily: typography.body.fontFamily,
    textAlign: 'center',
  },
  destructiveButton: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.destructiveSoft,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.destructiveSoftBorder,
  },
  destructiveText: {
    color: colors.destructiveSoftForeground,
    fontWeight: '700',
    fontFamily: typography.body.fontFamily,
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'stretch',
  },
  actionButtonDisabled: {
    opacity: 0.55,
  },
  proHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  proTitleGroup: {
    flex: 1,
    gap: 4,
  },
  proTitle: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
    fontFamily: typography.display.fontFamily,
  },
  proStatusPill: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  proStatusPillActive: {
    borderColor: colors.accent,
    backgroundColor: 'rgba(247, 162, 36, 0.14)',
  },
  proStatusText: {
    color: colors.mutedForeground,
    fontSize: 11,
    fontWeight: '800',
    fontFamily: typography.body.fontFamily,
  },
  proStatusTextActive: {
    color: colors.accent,
  },
  proDescription: {
    color: colors.mutedForeground,
    marginTop: 10,
    lineHeight: 19,
    fontFamily: typography.body.fontFamily,
  },
  proPriceText: {
    color: colors.foreground,
    marginTop: 12,
    marginBottom: 12,
    fontWeight: '800',
    fontFamily: typography.body.fontFamily,
  },
  proRestoreButton: {
    flex: 1,
    marginTop: 0,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  secondaryActionButton: {
    marginTop: 12,
    alignSelf: 'flex-start',
    backgroundColor: colors.surface2,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  secondaryActionText: {
    color: colors.foreground,
    fontWeight: '700',
    fontFamily: typography.body.fontFamily,
  },
  inlineSecondaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surface2,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inlineSecondaryText: {
    color: colors.foreground,
    fontWeight: '700',
    fontFamily: typography.body.fontFamily,
  },
  screenDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: -16,
    marginBottom: 18,
  },
});
